-- Migration 005: Expand companies across 6 verticals
-- Adding 32 new companies (11 already exist) to reach 43+ total

-- ============================================================
-- CRYPTO EXCHANGES (additional: Kraken, KuCoin, Bybit, OKX, Bitget, Gemini, dYdX, Paxful)
-- Uniswap already exists from seed data
-- ============================================================

INSERT INTO companies (
  name, slug, description, short_description, website_url, logo_url,
  category_id, subcategory_id, tags, pricing_type, rating, review_count,
  is_featured, is_verified, affiliate_available, affiliate_url, affiliate_commission,
  countries_supported, pros, cons, features, founded_year, headquarters
) VALUES
(
  'Kraken',
  'kraken',
  'Kraken is one of the oldest and most trusted cryptocurrency exchanges, known for its robust security measures, comprehensive trading features, and strong regulatory compliance. Founded in 2011, Kraken serves millions of clients worldwide with spot trading, futures, staking, and OTC services.',
  'Trusted since 2011 with industry-leading security and low fees',
  'https://www.kraken.com',
  null,
  (SELECT id FROM categories WHERE slug = 'crypto-exchanges'),
  (SELECT id FROM subcategories WHERE slug = 'centralized-exchanges'),
  ARRAY['exchange', 'trading', 'futures', 'staking', 'otc', 'security'],
  'freemium',
  4.7,
  890,
  true,
  true,
  true,
  'https://www.kraken.com/signup?ref=YOUR_REF',
  '20% commission on trading fees',
  ARRAY['US', 'UK', 'EU', 'Canada', 'Australia', 'Japan'],
  ARRAY['Industry-leading security since 2011', 'Low maker-taker fees', 'Extensive coin selection with 200+ assets', 'Kraken Pro for advanced traders', 'Staking rewards up to 24%', 'Strong regulatory compliance'],
  ARRAY['Complex interface for beginners', 'Limited customer support channels', 'Fiat deposit fees', 'Not available in all US states'],
  '{"spot_trading": true, "futures": true, "staking": true, "otc": true, "margin": true, "nft_marketplace": false}',
  2011,
  'San Francisco, USA'
),
(
  'KuCoin',
  'kucoin',
  'KuCoin is a global cryptocurrency exchange known for listing a wide variety of altcoins early, making it a favorite among traders seeking the next big token. With competitive fees, a native KCS token, and robust trading bots built in, KuCoin offers something for every trader level.',
  'Top altcoin exchange with built-in trading bots and low fees',
  'https://www.kucoin.com',
  null,
  (SELECT id FROM categories WHERE slug = 'crypto-exchanges'),
  (SELECT id FROM subcategories WHERE slug = 'centralized-exchanges'),
  ARRAY['exchange', 'altcoins', 'trading-bots', 'kcs', 'futures', 'lending'],
  'freemium',
  4.5,
  720,
  false,
  true,
  true,
  'https://www.kucoin.com/ucenter/signup?ref=YOUR_REF',
  '20% commission on trading fees',
  ARRAY['Global', 'Not available in US'],
  ARRAY['Huge altcoin selection (700+ tokens)', 'Built-in trading bots', 'Low trading fees (0.1%)', 'KCS token holder rewards', 'Lending and staking programs', 'Futures and margin trading'],
  ARRAY['Not available for US residents', 'Customer support can be slow', 'Some regulatory uncertainty', 'Interface can be overwhelming'],
  '{"spot_trading": true, "futures": true, "bots": true, "lending": true, "staking": true, "nft_marketplace": true}',
  2017,
  'Seychelles'
),
(
  'Bybit',
  'bybit',
  'Bybit is a leading cryptocurrency derivatives exchange offering up to 100x leverage on perpetual contracts. Known for its high-speed matching engine and deep liquidity, Bybit serves millions of traders worldwide with spot, futures, and options trading.',
  'High-leverage derivatives exchange with deep liquidity',
  'https://www.bybit.com',
  null,
  (SELECT id FROM categories WHERE slug = 'crypto-exchanges'),
  (SELECT id FROM subcategories WHERE slug = 'centralized-exchanges'),
  ARRAY['exchange', 'derivatives', 'futures', 'leverage', 'copy-trading'],
  'freemium',
  4.6,
  650,
  true,
  true,
  true,
  'https://www.bybit.com/register?ref=YOUR_REF',
  '30% commission on trading fees',
  ARRAY['Global', 'Not available in US'],
  ARRAY['Industry-leading derivatives platform', 'Up to 100x leverage', 'Copy trading feature', 'Fast matching engine (100K TPS)', 'Earn products available', 'Responsive mobile app'],
  ARRAY['Not available for US residents', 'High leverage carries significant risk', 'Regulatory concerns in some regions', 'Spot trading less developed than derivatives'],
  '{"spot_trading": true, "futures": true, "options": true, "copy_trading": true, "earn": true, "leverage": 100}',
  2018,
  'Dubai, UAE'
),
(
  'OKX',
  'okx',
  'OKX is a comprehensive crypto exchange and Web3 ecosystem offering spot trading, derivatives, DeFi, and NFT marketplace access. With its own layer-2 network (X Layer) and cross-chain bridge, OKX provides a full-spectrum crypto experience.',
  'Full-stack crypto platform with Web3 wallet and DEX aggregator',
  'https://www.okx.com',
  null,
  (SELECT id FROM categories WHERE slug = 'crypto-exchanges'),
  (SELECT id FROM subcategories WHERE slug = 'centralized-exchanges'),
  ARRAY['exchange', 'defi', 'nft', 'web3', 'x-layer', 'bridge'],
  'freemium',
  4.5,
  580,
  false,
  true,
  true,
  'https://www.okx.com/join/YOUR_REF',
  '30% commission on trading fees',
  ARRAY['Global', 'Not available in US'],
  ARRAY['Comprehensive Web3 ecosystem', 'Integrated DeFi and NFT features', 'OKX Web3 wallet with DEX aggregator', 'X Layer L2 network', 'Low trading fees', 'Copy trading'],
  ARRAY['Not available for US residents', 'Complex platform for beginners', 'Regulatory uncertainty', 'Customer support response times'],
  '{"spot_trading": true, "futures": true, "defi": true, "nft_marketplace": true, "web3_wallet": true, "dex_aggregator": true}',
  2017,
  'Seychelles'
),
(
  'Bitget',
  'bitget',
  'Bitget is a fast-growing crypto exchange specializing in copy trading and derivatives. With a native BGB token, spot trading, futures, and an innovative copy trading system, Bitget has become popular among traders looking to follow successful strategies.',
  'Leading copy trading exchange with futures and spot markets',
  'https://www.bitget.com',
  null,
  (SELECT id FROM categories WHERE slug = 'crypto-exchanges'),
  (SELECT id FROM subcategories WHERE slug = 'centralized-exchanges'),
  ARRAY['exchange', 'copy-trading', 'futures', 'bgb', 'derivatives'],
  'freemium',
  4.4,
  490,
  false,
  true,
  true,
  'https://www.bitget.com/referral?ref=YOUR_REF',
  '20% commission on trading fees',
  ARRAY['Global', 'Not available in US'],
  ARRAY['Industry-leading copy trading', 'Low trading fees', 'BGB token rewards', 'Futures with high liquidity', 'Launchpad for new tokens', 'Multi-language support'],
  ARRAY['Not available for US residents', 'Relatively newer exchange', 'Some regulatory concerns', 'Limited fiat options'],
  '{"spot_trading": true, "futures": true, "copy_trading": true, "earn": true, "launchpad": true}',
  2018,
  'Singapore'
),
(
  'Gemini',
  'gemini',
  'Gemini is a US-based cryptocurrency exchange founded by the Winklevoss twins, known for its strong regulatory compliance, insurance coverage, and institutional-grade security. Ideal for users prioritizing trust and compliance.',
  'Regulated US exchange with insurance and institutional trust',
  'https://www.gemini.com',
  null,
  (SELECT id FROM categories WHERE slug = 'crypto-exchanges'),
  (SELECT id FROM subcategories WHERE slug = 'centralized-exchanges'),
  ARRAY['exchange', 'regulated', 'insurance', 'institutional', 'nft', 'earn'],
  'freemium',
  4.3,
  350,
  false,
  true,
  true,
  'https://www.gemini.com/share/YOUR_REF',
  '$10 per referral signup',
  ARRAY['US', 'UK', 'Canada', 'Singapore', 'Hong Kong'],
  ARRAY['Regulated and licensed in US', 'Digital asset insurance coverage', 'Institutional-grade security', 'Gemini Earn for passive income', 'NFT marketplace', 'Clean intuitive interface'],
  ARRAY['Higher fees than competitors', 'Limited altcoin selection', 'Active Trader interface separate', 'Account verification can be slow'],
  '{"spot_trading": true, "futures": false, "earn": true, "nft_marketplace": true, "insurance": true, "institutional": true}',
  2014,
  'New York, USA'
),
(
  'dYdX',
  'dydx',
  'dYdX is a decentralized perpetuals exchange built on its own app-chain, offering fully on-chain order books with up to 20x leverage. As a leader in DeFi derivatives, dYdX provides a non-custodial, permissionless trading experience.',
  'Decentralized perpetuals exchange with on-chain order book',
  'https://dydx.exchange',
  null,
  (SELECT id FROM categories WHERE slug = 'crypto-exchanges'),
  (SELECT id FROM subcategories WHERE slug = 'decentralized-exchanges'),
  ARRAY['dex', 'perpetuals', 'defi', 'leverage', 'on-chain', 'trading'],
  'free',
  4.4,
  280,
  false,
  true,
  false,
  null,
  null,
  ARRAY['Global'],
  ARRAY['Fully on-chain order book', 'Non-custodial trading', 'Up to 20x leverage', 'No KYC required', 'Deep liquidity for major pairs', 'Custom app-chain for performance'],
  ARRAY['Limited trading pairs', 'Ethereum gas fees for deposits', 'No spot trading', 'Complex for beginners', 'Smart contract risk'],
  '{"perpetuals": true, "on_chain_orderbook": true, "leverage": 20, "spot_trading": false, "kyc": false}',
  2017,
  'San Francisco, USA'
),
(
  'Paxful',
  'paxful',
  'Paxful is a leading peer-to-peer Bitcoin marketplace connecting buyers and sellers directly with over 350 payment methods. Ideal for users in regions with limited banking access, Paxful makes Bitcoin accessible to everyone.',
  'P2P Bitcoin marketplace with 350+ payment methods',
  'https://www.paxful.com',
  null,
  (SELECT id FROM categories WHERE slug = 'crypto-exchanges'),
  (SELECT id FROM subcategories WHERE slug = 'p2p-exchanges'),
  ARRAY['p2p', 'bitcoin', 'marketplace', 'no-kyc', 'payment-methods'],
  'free',
  4.2,
  320,
  false,
  true,
  true,
  'https://www.paxful.com/?ref=YOUR_REF',
  '50% escrow fee commission',
  ARRAY['Global'],
  ARRAY['350+ payment methods', 'No KYC for basic trading', 'Escrow protection', 'Accessible in developing countries', 'Paxful Wallet', 'Educational resources'],
  ARRAY['Bitcoin only', 'Higher premiums on P2P trades', 'Scam risk without caution', 'Customer support slow', 'Limited trading features'],
  '{"p2p": true, "payment_methods": 350, "coins": 1, "escrow": true, "kyc_optional": true}',
  2015,
  'Wilmington, USA'
),

-- ============================================================
-- HARDWARE WALLETS (additional: Ledger Nano S Plus, Trezor Safe 3, Keystone Pro 3)
-- ============================================================
(
  'Ledger Nano S Plus',
  'ledger-nano-s-plus',
  'The Ledger Nano S Plus is an affordable hardware wallet that provides the same military-grade security as the Nano X, but without Bluetooth connectivity. Supporting over 5,500 coins and tokens, it is an excellent entry-level cold storage solution.',
  'Affordable Ledger hardware wallet with top-tier security',
  'https://www.ledger.com',
  null,
  (SELECT id FROM categories WHERE slug = 'hardware-wallets'),
  (SELECT id FROM subcategories WHERE slug = 'ledger-devices'),
  ARRAY['hardware-wallet', 'cold-storage', 'security', 'affordable', 'ledger'],
  'paid',
  4.6,
  510,
  false,
  true,
  true,
  'https://shop.ledger.com/pages/ledger-nano-s-plus?r=YOUR_REF',
  '15% commission on sales',
  ARRAY['Global'],
  ARRAY['Same security as Nano X at lower price', '5,500+ supported coins', 'Ledger Live integration', 'USB-C connectivity', 'Large screen for a budget wallet', 'No battery to worry about'],
  ARRAY['No Bluetooth', 'Wired connection required', 'Limited app storage vs Nano X', 'No mobile companion without OTG cable'],
  '{"bluetooth": false, "usb_type": "USB-C", "storage_count": 100, "security_chip": "CC EAL5+", "screen": "128x64px OLED"}',
  2022,
  'Paris, France'
),
(
  'Trezor Safe 3',
  'trezor-safe-3',
  'The Trezor Safe 3 is an affordable, open-source hardware wallet featuring a Secure Element chip and Shamir Backup support. It brings premium Trezor security to a budget-friendly price point, making cold storage accessible to more users.',
  'Budget open-source hardware wallet with Secure Element',
  'https://trezor.io',
  null,
  (SELECT id FROM categories WHERE slug = 'hardware-wallets'),
  (SELECT id FROM subcategories WHERE slug = 'trezor-devices'),
  ARRAY['hardware-wallet', 'cold-storage', 'open-source', 'secure-element', 'shamir'],
  'paid',
  4.5,
  280,
  true,
  true,
  true,
  'https://trezor.io/trezor-safe-3?ref=YOUR_REF',
  '10% commission',
  ARRAY['Global'],
  ARRAY['Affordable price point ($79)', 'Open-source firmware', 'Secure Element chip', 'Shamir Backup support', 'USB-C connectivity', 'Trezor Suite integration'],
  ARRAY['No touchscreen', 'No Bluetooth', 'Newer device with fewer reviews', 'Limited screen size'],
  '{"touchscreen": false, "usb_type": "USB-C", "secure_element": true, "shamir_backup": true, "fido2": true}',
  2023,
  'Prague, Czech Republic'
),
(
  'Keystone Pro 3',
  'keystone-pro-3',
  'The Keystone Pro 3 is a premium hardware wallet featuring a 4-inch touchscreen, fingerprint authentication, and multi-chain support. Its air-gapped signing via QR codes provides maximum security without USB or Bluetooth connections.',
  'Air-gapped hardware wallet with QR signing and fingerprint auth',
  'https://keyst.one',
  null,
  (SELECT id FROM categories WHERE slug = 'hardware-wallets'),
  null,
  ARRAY['hardware-wallet', 'cold-storage', 'air-gapped', 'qr-code', 'fingerprint'],
  'paid',
  4.4,
  180,
  false,
  true,
  true,
  'https://keyst.one/?ref=YOUR_REF',
  '12% commission',
  ARRAY['Global'],
  ARRAY['Air-gapped QR code signing', '4-inch touchscreen display', 'Fingerprint authentication', 'Multi-chain support', 'No USB/Bluetooth attack surface', 'Open-source firmware'],
  ARRAY['QR signing can be slow', 'Higher price ($139)', 'Bulkier than competitors', 'Limited mobile app features'],
  '{"touchscreen": true, "air_gapped": true, "fingerprint": true, "qr_signing": true, "screen_size": "4 inch", "battery": "1100mAh"}',
  2020,
  'Shenzhen, China'
),

-- ============================================================
-- CRYPTO TAX SOFTWARE (CoinLedger, TokenTax, Crypto Tax Calculator)
-- ============================================================
(
  'CoinLedger',
  'coinledger',
  'CoinLedger (formerly CryptoTrader.Tax) is a user-friendly crypto tax software designed for both casual investors and professional traders. It automatically imports transactions from exchanges and wallets to generate compliant tax reports.',
  'Simple crypto tax software with automatic exchange imports',
  'https://www.coinledger.io',
  null,
  (SELECT id FROM categories WHERE slug = 'crypto-tax-software'),
  null,
  ARRAY['tax', 'accounting', 'reporting', 'imports', 'turbotax'],
  'freemium',
  4.5,
  390,
  true,
  true,
  true,
  'https://www.coinledger.io/?ref=YOUR_REF',
  '25% commission',
  ARRAY['US', 'UK', 'Canada', 'Australia'],
  ARRAY['Very user-friendly interface', 'Automatic exchange imports', 'TurboTax and TaxAct integration', 'DeFi and NFT support', 'CPA-approved reports', 'Quick report generation'],
  ARRAY['Free tier very limited', 'Some complex DeFi transactions missed', 'International tax methods limited', 'Pricing based on transaction count'],
  '{"exchanges": 400, "turbotax": true, "defi": true, "nft": true, "countries": 5}',
  2018,
  'Kansas City, USA'
),
(
  'TokenTax',
  'tokentax',
  'TokenTax is a premium crypto tax platform offering both DIY software and full-service CPA support. Specializing in complex DeFi transactions and NFT tax reporting, TokenTax is ideal for high-net-worth individuals and professional traders.',
  'Premium crypto tax service with CPA support for complex portfolios',
  'https://tokentax.co',
  null,
  (SELECT id FROM categories WHERE slug = 'crypto-tax-software'),
  null,
  ARRAY['tax', 'cpa', 'defi', 'nft', 'accounting', 'premium'],
  'paid',
  4.3,
  210,
  false,
  true,
  true,
  'https://tokentax.co/?ref=YOUR_REF',
  '20% commission',
  ARRAY['US'],
  ARRAY['Full-service CPA support', 'Complex DeFi transaction handling', 'NFT tax reporting', 'Audit support available', 'Custom tax strategies', 'White-glove service tier'],
  ARRAY['Expensive premium tiers', 'US-focused only', 'DIY tier has limited features', 'Slow customer support at times'],
  '{"exchanges": 50, "cpa_support": true, "defi": true, "nft": true, "audit_support": true}',
  2017,
  'New York, USA'
),
(
  'Crypto Tax Calculator',
  'crypto-tax-calculator',
  'Crypto Tax Calculator is an Australian-born crypto tax platform that supports multiple countries and tax methods. Known for its accurate handling of DeFi protocols, margin trading, and income events, it generates comprehensive tax reports.',
  'Multi-country crypto tax calculator with excellent DeFi support',
  'https://cryptotaxcalculator.io',
  null,
  (SELECT id FROM categories WHERE slug = 'crypto-tax-software'),
  null,
  ARRAY['tax', 'defi', 'margin-trading', 'accounting', 'international'],
  'freemium',
  4.4,
  260,
  false,
  true,
  true,
  'https://cryptotaxcalculator.io/?ref=YOUR_REF',
  '20% commission',
  ARRAY['Australia', 'US', 'UK', 'Canada', 'Germany', 'Japan'],
  ARRAY['Multi-country tax support', 'Excellent DeFi handling', 'Margin trading tax calculations', 'Income and capital gains reporting', 'CSV and API imports', 'Accurate historical pricing'],
  ARRAY['Interface can be complex', 'Free tier very limited', 'Some exchange sync issues', 'Customer support response time'],
  '{"exchanges": 200, "countries": 30, "defi": true, "margin_trading": true, "api": true}',
  2018,
  'Sydney, Australia'
),

-- ============================================================
-- TRADING BOTS (Pionex, Cryptohopper, Bitsgap, TradeSanta)
-- ============================================================
(
  'Pionex',
  'pionex',
  'Pionex is a crypto exchange with 16 built-in trading bots, making automated trading accessible without external tools. Its grid trading bots, DCA bots, and arbitrage bots are free to use with low trading fees, ideal for passive income seekers.',
  'Exchange with 16 free built-in trading bots for automated strategies',
  'https://www.pionex.com',
  null,
  (SELECT id FROM categories WHERE slug = 'trading-bots'),
  null,
  ARRAY['trading-bot', 'grid-bot', 'dca', 'arbitrage', 'automation', 'exchange'],
  'freemium',
  4.6,
  520,
  true,
  true,
  true,
  'https://www.pionex.com/en/signup?ref=YOUR_REF',
  '20% commission on trading fees',
  ARRAY['Global', 'Not available in US some states'],
  ARRAY['16 free built-in trading bots', 'No extra subscription needed', 'Low trading fees (0.05%)', 'Grid trading and arbitrage bots', 'Liquidity from Binance and Huobi', 'Mobile-first design'],
  ARRAY['Limited to Pionex exchange', 'Not available in some US states', 'No custom bot strategies', 'Withdrawal fees can add up'],
  '{"bots": 16, "exchange": true, "grid_bot": true, "dca_bot": true, "arbitrage_bot": true, "copy_trading": true}',
  2019,
  'Singapore'
),
(
  'Cryptohopper',
  'cryptohopper',
  'Cryptohopper is an automated crypto trading bot platform with cloud-based operation, strategy marketplace, and social trading features. Supporting multiple exchanges, it allows users to automate strategies, backtest, and follow signal providers.',
  'Cloud-based trading bot with strategy marketplace and signals',
  'https://www.cryptohopper.com',
  null,
  (SELECT id FROM categories WHERE slug = 'trading-bots'),
  null,
  ARRAY['trading-bot', 'cloud', 'signals', 'backtesting', 'marketplace', 'automation'],
  'freemium',
  4.3,
  340,
  false,
  true,
  true,
  'https://www.cryptohopper.com/?ref=YOUR_REF',
  '25% commission',
  ARRAY['Global'],
  ARRAY['Cloud-based (runs 24/7)', 'Strategy marketplace', 'Signal provider following', 'Backtesting engine', 'Multi-exchange support', 'Visual strategy designer'],
  ARRAY['Subscription pricing can add up', 'Marketplace strategies not always profitable', 'Learning curve for custom strategies', 'Some features locked behind higher tiers'],
  '{"exchanges": 12, "backtesting": true, "marketplace": true, "signals": true, "cloud": true, "visual_designer": true}',
  2017,
  'Amsterdam, Netherlands'
),
(
  'Bitsgap',
  'bitsgap',
  'Bitsgap is a multi-exchange trading platform featuring grid bots, DCA bots, and a smart order terminal. Known for its intuitive interface and real-time portfolio tracking across 25+ exchanges, it simplifies automated crypto trading.',
  'Intuitive multi-exchange trading platform with grid and DCA bots',
  'https://bitsgap.com',
  null,
  (SELECT id FROM categories WHERE slug = 'trading-bots'),
  null,
  ARRAY['trading-bot', 'grid-bot', 'dca', 'multi-exchange', 'portfolio', 'terminal'],
  'freemium',
  4.4,
  290,
  false,
  true,
  true,
  'https://bitsgap.com/?ref=YOUR_REF',
  '20% commission',
  ARRAY['Global'],
  ARRAY['Clean intuitive interface', 'Multi-exchange portfolio view', 'Grid and DCA bots', 'Smart order terminal', 'Demo mode for testing', '25+ exchange connections'],
  ARRAY['Free tier very limited', 'Only 2 bots on free plan', 'No futures trading support', 'Higher tiers expensive for casual users'],
  '{"exchanges": 25, "bots": 2, "grid_bot": true, "dca_bot": true, "demo_mode": true, "terminal": true}',
  2018,
  'Tallinn, Estonia'
),
(
  'TradeSanta',
  'tradesanta',
  'TradeSanta is a cloud-based crypto trading bot designed for simplicity. With pre-built strategies like Grid and DCA, it makes automated trading accessible to beginners while offering enough customization for experienced traders.',
  'Simple cloud trading bot with pre-built strategies for beginners',
  'https://tradesanta.com',
  null,
  (SELECT id FROM categories WHERE slug = 'trading-bots'),
  null,
  ARRAY['trading-bot', 'grid-bot', 'dca', 'cloud', 'beginner-friendly', 'automation'],
  'freemium',
  4.1,
  180,
  false,
  true,
  true,
  'https://tradesanta.com/?ref=YOUR_REF',
  '30% commission',
  ARRAY['Global'],
  ARRAY['Very beginner-friendly', 'Pre-built strategy templates', 'Cloud-based (24/7 operation)', 'Multi-exchange support', 'Low starting price', 'Quick setup process'],
  ARRAY['Limited advanced features', 'Fewer bot types than competitors', 'No backtesting on free plan', 'Customer support limited'],
  '{"exchanges": 8, "bots": 2, "grid_bot": true, "dca_bot": true, "backtesting": false, "cloud": true}',
  2018,
  'London, UK'
),

-- ============================================================
-- CLOUD MINING (NiceHash, ECOS, BeMine, Compass Mining)
-- ============================================================
(
  'NiceHash',
  'nicehash',
  'NiceHash is the leading cryptocurrency hash rate marketplace, connecting miners and buyers of mining power. Users can either sell their GPU/ASIC hash power or buy it to mine any coin, making it a flexible platform for both miners and investors.',
  'Leading hash rate marketplace for buying and selling mining power',
  'https://www.nicehash.com',
  null,
  (SELECT id FROM categories WHERE slug = 'cloud-mining'),
  null,
  ARRAY['cloud-mining', 'hashrate', 'marketplace', 'gpu-mining', 'asic', 'buy-sell'],
  'freemium',
  4.3,
  450,
  true,
  true,
  true,
  'https://www.nicehash.com/?ref=YOUR_REF',
  '5% commission on marketplace fees',
  ARRAY['Global'],
  ARRAY['Flexible buy/sell hash rate model', 'Supports GPU and ASIC mining', 'Auto-switch to most profitable coins', 'NiceHash QuickMiner for easy setup', 'Lightning Network payouts', 'Active marketplace liquidity'],
  ARRAY['Marketplace fees can be high', 'Past security breach (2017)', 'Earnings fluctuate with market', 'Less profitable than solo mining in bull markets'],
  '{"marketplace": true, "gpu_mining": true, "asic_mining": true, "auto_switch": true, "lightning_payouts": true}',
  2014,
  'Ljubljana, Slovenia'
),
(
  'ECOS',
  'ecos',
  'ECOS is a cloud mining platform offering long-term Bitcoin mining contracts with data centers in Armenia. Users can purchase hashrate contracts without managing hardware, making Bitcoin mining accessible as a passive investment.',
  'Bitcoin cloud mining contracts with data centers in Armenia',
  'https://ecos.am',
  null,
  (SELECT id FROM categories WHERE slug = 'cloud-mining'),
  null,
  ARRAY['cloud-mining', 'bitcoin', 'contracts', 'passive-income', 'data-center'],
  'paid',
  4.0,
  150,
  false,
  true,
  true,
  'https://ecos.am/?ref=YOUR_REF',
  '7% commission on contract sales',
  ARRAY['Global'],
  ARRAY['No hardware management needed', 'Long-term contracts available', 'Data center in Free Economic Zone', 'Daily payouts', 'Mobile app for monitoring', 'Transparent pricing calculator'],
  ARRAY['ROI depends on Bitcoin price', 'Contracts are non-refundable', 'Limited to Bitcoin mining only', 'Lower profit margins than self-mining'],
  '{"contracts": true, "coins": 1, "data_center": "Armenia", "payouts": "daily", "mobile_app": true}',
  2017,
  'Yerevan, Armenia'
),
(
  'BeMine',
  'bemine',
  'BeMine offers a unique approach to cloud mining by allowing users to purchase shares of ASIC miners rather than full contracts. This fractional ownership model makes mining accessible at lower entry points with real hardware backing each share.',
  'Fractional ASIC mining shares with real hardware ownership',
  'https://bemine.club',
  null,
  (SELECT id FROM categories WHERE slug = 'cloud-mining'),
  null,
  ARRAY['cloud-mining', 'asic', 'fractional', 'shares', 'bitcoin'],
  'paid',
  4.0,
  80,
  false,
  true,
  true,
  'https://bemine.club/?ref=YOUR_REF',
  '10% commission on share sales',
  ARRAY['Global'],
  ARRAY['Fractional ASIC ownership', 'Lower entry point than full miners', 'Real hardware backing shares', 'Daily payouts', 'Mining farm hosting available', 'Transparent operations'],
  ARRAY['Limited track record', 'ROI depends on market conditions', 'Only Bitcoin and a few altcoins', 'Withdrawal minimums apply'],
  '{"fractional_mining": true, "asic_hosting": true, "coins": 3, "payouts": "daily", "share_model": true}',
  2018,
  'Moscow, Russia'
),
(
  'Compass Mining',
  'compass-mining',
  'Compass Mining is a Bitcoin mining infrastructure company offering ASIC hardware sales, hosting services, and co-location solutions. It enables individuals and institutions to participate in Bitcoin mining without managing their own facility.',
  'Bitcoin mining infrastructure with ASIC sales and hosting',
  'https://compassmining.io',
  null,
  (SELECT id FROM categories WHERE slug = 'cloud-mining'),
  null,
  ARRAY['cloud-mining', 'asic', 'hosting', 'bitcoin', 'infrastructure', 'co-location'],
  'paid',
  4.2,
  190,
  true,
  true,
  true,
  'https://compassmining.io/?ref=YOUR_REF',
  '5% commission on hardware sales',
  ARRAY['US', 'Global'],
  ARRAY['Full-service mining infrastructure', 'ASIC hardware sales at competitive prices', 'Hosting in US data centers', 'Institutional-grade facilities', 'Transparent pricing', 'Secondary market for used miners'],
  ARRAY['High minimum investment', 'US data centers only', 'Lead times on hardware delivery', 'Power costs not included in hosting'],
  '{"hardware_sales": true, "hosting": true, "co_location": true, "coins": 1, "institutional": true, "secondary_market": true}',
  2020,
  'Portland, USA'
),

-- ============================================================
-- SECURITY TOOLS (Fireblocks, CoolWallet Pro, SafePal S1, Revoke.cash)
-- ============================================================
(
  'Fireblocks',
  'fireblocks',
  'Fireblocks is an enterprise-grade digital asset security platform providing MPC wallet infrastructure, tokenization, and DeFi access for institutions. Used by major exchanges and financial institutions, it secures billions in digital assets.',
  'Enterprise MPC wallet infrastructure for institutional digital asset security',
  'https://www.fireblocks.com',
  null,
  (SELECT id FROM categories WHERE slug = 'defi-tools'),
  null,
  ARRAY['security', 'mpc-wallet', 'institutional', 'tokenization', 'defi', 'enterprise'],
  'enterprise',
  4.8,
  120,
  false,
  true,
  false,
  null,
  null,
  ARRAY['Global'],
  ARRAY['MPC-based key management', 'Used by 1800+ institutions', 'DeFi and CeFi access', 'Tokenization engine', 'Insurance coverage up to $1B', 'SOC 2 Type II certified'],
  ARRAY['Enterprise pricing only', 'Not for individual retail users', 'Complex implementation', 'Requires institutional onboarding'],
  '{"mpc_wallet": true, "tokenization": true, "defi_access": true, "insurance": "$1B", "institutional": true, "soc2": true}',
  2018,
  'New York, USA'
),
(
  'CoolWallet Pro',
  'coolwallet-pro',
  'The CoolWallet Pro is a credit-card-sized Bluetooth hardware wallet with EAL6+ security certification. Supporting 30+ blockchains and DeFi staking, it combines portability with military-grade security for mobile-first crypto users.',
  'Credit-card-sized Bluetooth hardware wallet with EAL6+ certification',
  'https://www.coolwallet.io',
  null,
  (SELECT id FROM categories WHERE slug = 'hardware-wallets'),
  null,
  ARRAY['hardware-wallet', 'cold-storage', 'bluetooth', 'mobile', 'defi', 'staking'],
  'paid',
  4.3,
  200,
  false,
  true,
  true,
  'https://www.coolwallet.io/?ref=YOUR_REF',
  '10% commission',
  ARRAY['Global'],
  ARRAY['Credit card form factor', 'EAL6+ security certification', 'Bluetooth connectivity', '30+ blockchain support', 'In-app DeFi staking', 'Water and tamper resistant'],
  ARRAY['Higher price ($149)', 'Limited to mobile companion', 'Smaller screen', 'Fewer supported coins than Ledger'],
  '{"bluetooth": true, "form_factor": "credit_card", "security_chip": "EAL6+", "blockchains": 30, "staking": true, "water_resistant": true}',
  2018,
  'Taipei, Taiwan'
),
(
  'SafePal S1',
  'safepal-s1',
  'The SafePal S1 is an affordable air-gapped hardware wallet backed by Binance Labs. Featuring QR code signing, a 1.3-inch screen, and support for 30+ blockchains, it provides secure cold storage at a budget-friendly price.',
  'Affordable air-gapped hardware wallet backed by Binance Labs',
  'https://www.safepal.com',
  null,
  (SELECT id FROM categories WHERE slug = 'hardware-wallets'),
  null,
  ARRAY['hardware-wallet', 'cold-storage', 'air-gapped', 'qr-code', 'binance', 'affordable'],
  'paid',
  4.2,
  320,
  false,
  true,
  true,
  'https://www.safepal.com/?ref=YOUR_REF',
  '10% commission',
  ARRAY['Global'],
  ARRAY['Very affordable ($49.99)', 'Air-gapped QR code signing', 'Binance Labs backed', '30+ blockchain support', 'No USB or Bluetooth', 'Mobile app integration'],
  ARRAY['QR signing can be slow', 'Small screen', 'Limited DeFi features', 'Relatively new product'],
  '{"air_gapped": true, "qr_signing": true, "screen": "1.3 inch", "blockchains": 30, "price": 49.99, "binance_backed": true}',
  2018,
  'Shenzhen, China'
),
(
  'Revoke.cash',
  'revoke-cash',
  'Revoke.cash is a free security tool that allows users to review and revoke token approvals on Ethereum and EVM-compatible chains. Essential for DeFi users, it helps prevent unauthorized access to wallets by managing smart contract permissions.',
  'Free tool to review and revoke risky token approvals on EVM chains',
  'https://revoke.cash',
  null,
  (SELECT id FROM categories WHERE slug = 'defi-tools'),
  null,
  ARRAY['security', 'approval-revoke', 'defi', 'evm', 'token-approval', 'free'],
  'free',
  4.6,
  180,
  false,
  true,
  false,
  null,
  null,
  ARRAY['Global'],
  ARRAY['Free to use', 'One-click revoke approvals', 'Multi-chain support', 'Essential DeFi security tool', 'No account required', 'Open source'],
  ARRAY['No notifications for risky approvals', 'Manual checking required', 'Cannot prevent all exploits', 'Limited to EVM chains'],
  '{"multi_chain": true, "open_source": true, "free": true, "evm_only": true, "one_click_revoke": true}',
  2020,
  'Decentralized'
),

-- ============================================================
-- ADDITIONAL COMPANIES for underrepresented categories
-- ============================================================

-- Mining Hardware
(
  'Bitmain',
  'bitmain',
  'Bitmain is the worlds leading producer of ASIC mining hardware, known for its Antminer series. Dominating the Bitcoin mining industry, Bitmain provides the hardware that powers a significant portion of the global Bitcoin network hashrate.',
  'World leading ASIC miner manufacturer with the Antminer series',
  'https://www.bitmain.com',
  null,
  (SELECT id FROM categories WHERE slug = 'mining-hardware'),
  null,
  ARRAY['asic', 'mining', 'antminer', 'bitcoin', 'hardware'],
  'paid',
  4.2,
  380,
  true,
  true,
  true,
  'https://shop.bitmain.com/?ref=YOUR_REF',
  '5% commission on hardware sales',
  ARRAY['Global'],
  ARRAY['Industry-leading ASIC miners', 'High hashrate efficiency', 'Wide product range', 'Global distribution', 'Aftermarket support', 'Firmware updates'],
  ARRAY['Hardware can be expensive', 'Long shipping times', 'Noisy and power-hungry', 'Warranty limitations'],
  '{"asic_miners": true, "product_line": "Antminer", "global_shipping": true, "firmware_updates": true}',
  2013,
  'Beijing, China'
),

-- Staking Platforms
(
  'Lido',
  'lido',
  'Lido is the leading liquid staking protocol for Ethereum and other PoS blockchains. Users can stake ETH without locking it up, receiving stETH tokens that can be used across DeFi protocols while still earning staking rewards.',
  'Largest liquid staking protocol for Ethereum and PoS chains',
  'https://lido.fi',
  null,
  (SELECT id FROM categories WHERE slug = 'staking-platforms'),
  null,
  ARRAY['staking', 'liquid-staking', 'steth', 'defi', 'ethereum', 'pos'],
  'free',
  4.7,
  430,
  true,
  true,
  false,
  null,
  null,
  ARRAY['Global'],
  ARRAY['Liquid staking (no lock-up)', 'stETH usable across DeFi', 'No minimum stake', 'Multi-chain support', 'DAO governance', 'High TVL and liquidity'],
  ARRAY['Smart contract risk', 'Staking fee (10%)', 'stETH/ETH depeg risk', 'Slashing risk'],
  '{"liquid_staking": true, "chains": 6, "fee": "10%", "tvl": "$30B+", "dao": true, "no_minimum": true}',
  2020,
  'Decentralized'
),

-- Portfolio Trackers
(
  'CoinMarketCap',
  'coinmarketcap',
  'CoinMarketCap is the most referenced crypto price tracking website, providing real-time data on 30,000+ cryptocurrencies across 1,000+ exchanges. Acquired by Binance in 2020, it remains the go-to resource for crypto market data and portfolio tracking.',
  'Most referenced crypto price tracker with 30,000+ coins',
  'https://coinmarketcap.com',
  null,
  (SELECT id FROM categories WHERE slug = 'portfolio-trackers'),
  null,
  ARRAY['price-tracking', 'portfolio', 'data', 'api', 'market-cap', 'rankings'],
  'free',
  4.6,
  860,
  true,
  true,
  true,
  'https://coinmarketcap.com/?ref=YOUR_REF',
  'Revenue share on API subscriptions',
  ARRAY['Global'],
  ARRAY['Most comprehensive coin data', 'Free portfolio tracker', 'Reliable price data API', 'Watchlist and alerts', 'Educational content', 'Mobile app'],
  ARRAY['Some data delayed on free tier', 'Binance ownership raises neutrality questions', 'API rate limits on free plan', 'Premium features behind paywall'],
  '{"tracked_coins": 30000, "exchanges": 1000, "api": true, "portfolio_tracker": true, "mobile_app": true, "watchlist": true}',
  2013,
  'Wilmington, USA'
),

-- AI Crypto Tools
(
  'Cryptoslate AI',
  'cryptoslate-ai',
  'Cryptoslate AI provides AI-powered crypto market analysis, sentiment tracking, and predictive insights. Combining natural language processing with on-chain data, it helps traders identify market trends and make data-driven decisions.',
  'AI-powered crypto market analysis and sentiment intelligence',
  'https://cryptoslate.com',
  null,
  (SELECT id FROM categories WHERE slug = 'ai-crypto-tools'),
  null,
  ARRAY['ai', 'sentiment', 'analysis', 'predictions', 'nlp', 'on-chain'],
  'freemium',
  4.2,
  120,
  true,
  true,
  true,
  'https://cryptoslate.com/?ref=YOUR_REF',
  '20% commission',
  ARRAY['Global'],
  ARRAY['AI-powered market insights', 'Sentiment analysis', 'On-chain data integration', 'Predictive trend indicators', 'Real-time alerts', 'Custom AI reports'],
  ARRAY['Predictions not always accurate', 'Premium tier expensive', 'Relatively new product', 'Limited historical data for AI training'],
  '{"ai_analysis": true, "sentiment": true, "on_chain": true, "predictions": true, "alerts": true, "reports": true}',
  2022,
  'Seattle, USA'
),

-- NFT Platforms
(
  'OpenSea',
  'opensea',
  'OpenSea is the largest NFT marketplace for buying, selling, and creating digital collectibles. Supporting Ethereum, Polygon, Klaytn, and other chains, it is the primary destination for NFT trading with millions of collections listed.',
  'Largest NFT marketplace with millions of digital collectibles',
  'https://opensea.io',
  null,
  (SELECT id FROM categories WHERE slug = 'nft-platforms'),
  (SELECT id FROM subcategories WHERE slug = 'nft-marketplaces'),
  ARRAY['nft', 'marketplace', 'ethereum', 'polygon', 'collectibles', 'trading'],
  'freemium',
  4.4,
  680,
  true,
  true,
  true,
  'https://opensea.io/?ref=YOUR_REF',
  '2.5% marketplace fee share',
  ARRAY['Global'],
  ARRAY['Largest NFT marketplace', 'Multi-chain support', 'Collection and item listings', 'Lazy minting for creators', 'Rarity tools and analytics', 'Seaport protocol'],
  ARRAY['High gas fees during peak times', 'Customer support slow', 'Wash trading concerns', 'Market share declining to competitors'],
  '{"marketplace": true, "chains": 4, "lazy_minting": true, "rarity_tools": true, "seaport_protocol": true}',
  2017,
  'New York, USA'
),

-- Payment Processors
(
  'BitPay',
  'bitpay',
  'BitPay is the oldest and most established cryptocurrency payment processor, enabling businesses to accept Bitcoin and crypto payments with seamless fiat conversion. Serving thousands of merchants worldwide, it bridges the gap between crypto and traditional commerce.',
  'Leading crypto payment processor for merchant Bitcoin acceptance',
  'https://bitpay.com',
  null,
  (SELECT id FROM categories WHERE slug = 'payment-processors'),
  null,
  ARRAY['payments', 'merchant', 'bitcoin', 'processing', 'crypto-card', 'invoices'],
  'freemium',
  4.3,
  290,
  true,
  true,
  true,
  'https://bitpay.com/?ref=YOUR_REF',
  '15% commission on processing fees',
  ARRAY['US', 'EU', 'Global'],
  ARRAY['Longest-running crypto payment processor', 'Instant fiat settlement', 'BitPay Card for spending', 'Invoice and billing system', 'Point-of-sale integration', 'No price volatility risk for merchants'],
  ARRAY['1% processing fee', 'Limited to certain cryptocurrencies', 'Business-focused (not for individuals)', 'KYC required'],
  '{"merchant_payments": true, "fiat_settlement": true, "debit_card": true, "pos_integration": true, "invoicing": true, "fee": "1%"}',
  2011,
  'Atlanta, USA'
),

-- Crypto News Sites
(
  'CoinDesk',
  'coindesk',
  'CoinDesk is the leading news site covering cryptocurrency, blockchain, and digital assets. Known for breaking news, investigative journalism, and the annual Consensus conference, it is a primary source of information for the crypto industry.',
  'Leading crypto and blockchain news with investigative journalism',
  'https://www.coindesk.com',
  null,
  (SELECT id FROM categories WHERE slug = 'crypto-news-sites'),
  null,
  ARRAY['news', 'media', 'journalism', 'blockchain', 'research', 'consensus'],
  'free',
  4.5,
  540,
  true,
  true,
  true,
  'https://www.coindesk.com/?ref=YOUR_REF',
  'CPA commission on subscriptions',
  ARRAY['Global'],
  ARRAY['Industry-leading journalism', 'Consensus conference organizer', 'Research and data products', 'Breaking news coverage', 'Podcast network', 'Price indexes'],
  ARRAY['Perceived editorial bias at times', 'Subscription required for some content', 'Ad-heavy experience', 'DCG parent company controversy'],
  '{"news": true, "research": true, "podcasts": true, "conference": true, "price_indexes": true, "subscription": true}',
  2013,
  'New York, USA'
),

-- Research Platforms
(
  'Messari',
  'messari',
  'Messari is a crypto research and data platform providing institutional-grade analysis, token profiles, and governance tracking. Used by investors and researchers, it delivers structured data and qualitative insights on thousands of crypto assets.',
  'Institutional-grade crypto research and structured data platform',
  'https://messari.io',
  null,
  (SELECT id FROM categories WHERE slug = 'research-platforms'),
  null,
  ARRAY['research', 'data', 'analytics', 'governance', 'due-diligence', 'institutional'],
  'freemium',
  4.6,
  310,
  false,
  true,
  true,
  'https://messari.io/?ref=YOUR_REF',
  '20% commission on subscriptions',
  ARRAY['Global'],
  ARRAY['Institutional-grade research', 'Structured asset profiles', 'Governance tracking', 'Custom screener and watchlists', 'Protocol metrics', 'Daily research briefs'],
  ARRAY['Premium tier expensive', 'Free tier limited', 'Focused on serious investors', 'Can be overwhelming for beginners'],
  '{"research": true, "asset_profiles": true, "governance": true, "screener": true, "protocol_metrics": true, "daily_briefs": true}',
  2018,
  'New York, USA'
),

-- Crypto Casinos
(
  'Stake.com',
  'stake-com',
  'Stake.com is the largest crypto casino and sportsbook, offering provably fair games, instant crypto deposits, and a massive selection of slots, table games, and sports betting. Popular globally for its VIP program and community features.',
  'Largest crypto casino with provably fair games and VIP rewards',
  'https://www.stake.com',
  null,
  (SELECT id FROM categories WHERE slug = 'crypto-casinos'),
  null,
  ARRAY['casino', 'gambling', 'provably-fair', 'sportsbook', 'crypto-betting', 'vip'],
  'free',
  4.4,
  780,
  true,
  true,
  true,
  'https://www.stake.com/?ref=YOUR_REF',
  'Revenue share on house edge',
  ARRAY['Global', 'Not available in US, UK, Australia'],
  ARRAY['Provably fair gaming', 'Instant crypto deposits/withdrawals', 'Huge game selection', 'VIP and rakeback program', 'Community and social features', 'Sports betting integrated'],
  ARRAY['Not available in US/UK/Australia', 'Gambling carries financial risk', 'Regulatory uncertainty', 'Can be addictive'],
  '{"provably_fair": true, "instant_payouts": true, "vip_program": true, "sports_betting": true, "rakeback": true, "community": true}',
  2017,
  'Curacao'
),

-- Launchpads
(
  'CoinList',
  'coinlist',
  'CoinList is a leading token launch platform that helps blockchain projects distribute tokens to the community. Known for hosting high-profile ICOs and token sales, CoinList provides due diligence, compliance, and distribution infrastructure.',
  'Leading token launch platform for high-profile crypto projects',
  'https://coinlist.co',
  null,
  (SELECT id FROM categories WHERE slug = 'launchpads'),
  null,
  ARRAY['launchpad', 'token-sale', 'ico', 'distribution', 'compliance', 'investing'],
  'freemium',
  4.3,
  240,
  true,
  true,
  true,
  'https://coinlist.co/?ref=YOUR_REF',
  'Variable per sale',
  ARRAY['US (accredited), Global'],
  ARRAY['High-profile token sales', 'Due diligence on projects', 'Compliance infrastructure', 'Lock-up and vesting management', 'Secondary market trading', 'Strong track record of successful launches'],
  ARRAY['Many sales sell out instantly', 'US access limited to accredited investors', 'High demand makes allocation difficult', 'Lock-up periods on many tokens'],
  '{"token_sales": true, "compliance": true, "secondary_market": true, "vesting": true, "due_diligence": true}',
  2017,
  'San Francisco, USA'
),

-- Crypto Education
(
  'Binance Academy',
  'binance-academy',
  'Binance Academy is a free educational platform offering comprehensive blockchain and cryptocurrency courses, tutorials, and glossaries. From beginner guides to advanced trading strategies, it covers the full spectrum of crypto knowledge.',
  'Free comprehensive crypto education by Binance',
  'https://academy.binance.com',
  null,
  (SELECT id FROM categories WHERE slug = 'crypto-education'),
  null,
  ARRAY['education', 'courses', 'tutorials', 'free', 'blockchain', 'trading'],
  'free',
  4.5,
  350,
  false,
  true,
  true,
  'https://academy.binance.com/?ref=YOUR_REF',
  'Traffic referral credit',
  ARRAY['Global'],
  ARRAY['Completely free', 'Wide range of topics', 'Multi-language support', 'Interactive quizzes', 'Glossary and reference tools', 'Video and article formats'],
  ARRAY['Binance-branded content', 'Some content promotes Binance products', 'No formal certification', 'Limited depth on advanced topics'],
  '{"courses": 300, "free": true, "languages": 30, "quizzes": true, "videos": true, "certification": false}',
  2018,
  'Decentralized'
),

-- Mining Pools
(
  'F2Pool',
  'f2pool',
  'F2Pool is one of the oldest and largest cryptocurrency mining pools, supporting 40+ coins including Bitcoin, Ethereum Classic, and Litecoin. Known for reliable payouts and professional mining infrastructure, it serves miners worldwide.',
  'Veteran mining pool supporting 40+ coins with reliable payouts',
  'https://www.f2pool.com',
  null,
  (SELECT id FROM categories WHERE slug = 'mining-pools'),
  null,
  ARRAY['mining-pool', 'bitcoin', 'multicoin', 'payouts', 'mining', 'infrastructure'],
  'free',
  4.3,
  220,
  false,
  true,
  true,
  'https://www.f2pool.com/?ref=YOUR_REF',
  '3% pool fee share',
  ARRAY['Global'],
  ARRAY['Supports 40+ coins', 'Reliable since 2013', 'PPS and PPS+ payout methods', 'Detailed mining statistics', 'Mobile monitoring app', 'Low minimum payouts'],
  ARRAY['Pool fee (2.5-5%)', 'Centralization concerns', 'Customer support limited', 'Some coins have higher minimums'],
  '{"coins": 40, "payout_methods": ["PPS", "PPS+"], "fee": "2.5%", "mobile_app": true, "stats": true}',
  2013,
  'Beijing, China'
),

-- Sportsbooks
(
  'Cloudbet',
  'cloudbet',
  'Cloudbet is a premium crypto sportsbook and casino offering competitive odds on 30+ sports with Bitcoin and crypto deposits. Known for high betting limits and instant payouts, it is a favorite among serious crypto bettors.',
  'Premium crypto sportsbook with high limits and instant payouts',
  'https://www.cloudbet.com',
  null,
  (SELECT id FROM categories WHERE slug = 'sportsbooks'),
  null,
  ARRAY['sportsbook', 'betting', 'crypto', 'bitcoin', 'casino', 'live-betting'],
  'free',
  4.2,
  340,
  true,
  true,
  true,
  'https://www.cloudbet.com/?ref=YOUR_REF',
  'Revenue share on house edge',
  ARRAY['Global', 'Not available in US, UK, Australia'],
  ARRAY['High betting limits', 'Instant crypto payouts', '30+ sports markets', 'Live betting and streaming', 'Welcome bonus up to 5 BTC', 'Provably fair casino'],
  ARRAY['Not available in US/UK/Australia', 'Gambling carries risk', 'Regulatory uncertainty', 'Limited fiat options'],
  '{"sports": 30, "live_betting": true, "high_limits": true, "instant_payouts": true, "welcome_bonus": "5 BTC", "provably_fair": true}',
  2013,
  'Curacao'
),

-- Software Wallets
(
  'Trust Wallet',
  'trust-wallet',
  'Trust Wallet is a popular multi-chain mobile wallet owned by Binance, supporting 70+ blockchains and 4.5M+ digital assets. With built-in DApp browser, staking, and swap features, it is a comprehensive Web3 wallet for mobile users.',
  'Multi-chain mobile wallet with DApp browser and 70+ chain support',
  'https://trustwallet.com',
  null,
  (SELECT id FROM categories WHERE slug = 'software-wallets'),
  (SELECT id FROM subcategories WHERE slug = 'mobile-wallets'),
  ARRAY['wallet', 'mobile', 'multi-chain', 'dapp-browser', 'staking', 'swap'],
  'free',
  4.5,
  720,
  true,
  true,
  true,
  'https://trustwallet.com/?ref=YOUR_REF',
  'Swap fee revenue share',
  ARRAY['Global'],
  ARRAY['70+ blockchain support', 'Built-in DApp browser', 'Staking rewards', 'Trust Wallet token (TWT)', 'Non-custodial', 'NFT display support'],
  ARRAY['Mobile only (no desktop)', 'Binance ownership concerns', 'Some DApp compatibility issues', 'Customer support limited'],
  '{"mobile_app": true, "chains": 70, "dapp_browser": true, "staking": true, "swap": true, "nft_support": true}',
  2017,
  'San Francisco, USA'
),

-- Analytics Platforms
(
  'Dune Analytics',
  'dune-analytics',
  'Dune Analytics is a community-driven crypto analytics platform where anyone can query blockchain data using SQL. Used by researchers, investors, and protocols, it makes on-chain data accessible through shared dashboards and visualizations.',
  'Community-driven on-chain analytics with SQL querying',
  'https://dune.com',
  null,
  (SELECT id FROM categories WHERE slug = 'analytics-platforms'),
  null,
  ARRAY['analytics', 'on-chain', 'sql', 'dashboards', 'data', 'community'],
  'freemium',
  4.7,
  280,
  false,
  true,
  true,
  'https://dune.com/?ref=YOUR_REF',
  '20% commission on subscriptions',
  ARRAY['Global'],
  ARRAY['Free SQL querying of on-chain data', 'Community-shared dashboards', 'Multi-chain support', 'No coding required for existing queries', 'Real-time data', 'Embeddable charts'],
  ARRAY['Free tier has query limits', 'Learning SQL required for custom queries', 'Some queries are slow', 'Premium needed for API access'],
  '{"sql_queries": true, "dashboards": true, "chains": 10, "community": true, "api": true, "embeddable": true}',
  2019,
  'Oslo, Norway'
);

-- Update best_of_lists titles to 2026
UPDATE best_of_lists SET title = 'Best Crypto Exchanges of 2026' WHERE slug = 'best-crypto-exchanges';
UPDATE best_of_lists SET title = 'Best Hardware Wallets 2026' WHERE slug = 'best-hardware-wallets';
UPDATE best_of_lists SET title = 'Best Crypto Tax Software 2026' WHERE slug = 'best-crypto-tax-software';