-- Insert categories with proper ordering
INSERT INTO categories (name, slug, description, icon, order_index) VALUES
('Crypto Exchanges', 'crypto-exchanges', 'Buy, sell, and trade cryptocurrencies on secure platforms', 'repeat', 1),
('Hardware Wallets', 'hardware-wallets', 'Cold storage devices for maximum crypto security', 'hard-drive', 2),
('Software Wallets', 'software-wallets', 'Desktop and mobile wallets for everyday crypto use', 'smartphone', 3),
('Trading Bots', 'trading-bots', 'Automated trading tools and algorithmic strategies', 'bot', 4),
('Crypto Tax Software', 'crypto-tax-software', 'Calculate and report your crypto taxes accurately', 'calculator', 5),
('Crypto Education', 'crypto-education', 'Learn blockchain and cryptocurrency fundamentals', 'graduation-cap', 6),
('Mining Hardware', 'mining-hardware', 'ASIC miners and GPU rigs for cryptocurrency mining', 'cpu', 7),
('Cloud Mining', 'cloud-mining', 'Remote mining contracts without hardware management', 'cloud', 8),
('Mining Pools', 'mining-pools', 'Join forces with other miners for consistent rewards', 'users', 9),
('Staking Platforms', 'staking-platforms', 'Earn passive income through crypto staking', 'lock', 10),
('DeFi Tools', 'defi-tools', 'Decentralized finance protocols and applications', 'layers', 11),
('Portfolio Trackers', 'portfolio-trackers', 'Monitor and manage your crypto investments', 'line-chart', 12),
('AI Crypto Tools', 'ai-crypto-tools', 'Artificial intelligence powered crypto solutions', 'brain', 13),
('Analytics Platforms', 'analytics-platforms', 'Deep insights and market analysis tools', 'bar-chart-2', 14),
('Research Platforms', 'research-platforms', 'Due diligence and fundamental analysis', 'search', 15),
('Crypto News Sites', 'crypto-news-sites', 'Stay updated with latest crypto news and trends', 'newspaper', 16),
('NFT Platforms', 'nft-platforms', 'Create, buy, sell and discover NFTs', 'image', 17),
('Launchpads', 'launchpads', 'Early access to new crypto projects and tokens', 'rocket', 18),
('Crypto Casinos', 'crypto-casinos', 'Online gambling with cryptocurrency payments', 'dice-5', 19),
('Sportsbooks', 'sportsbooks', 'Sports betting with crypto deposits and withdrawals', 'trophy', 20),
('Payment Processors', 'payment-processors', 'Accept and process crypto payments', 'credit-card', 21);

-- Insert subcategories
INSERT INTO subcategories (category_id, name, slug, description) VALUES
((SELECT id FROM categories WHERE slug = 'crypto-exchanges'), 'Centralized Exchanges', 'centralized-exchanges', 'Traditional exchanges with fiat on/off ramps'),
((SELECT id FROM categories WHERE slug = 'crypto-exchanges'), 'Decentralized Exchanges', 'decentralized-exchanges', 'DEX platforms with non-custodial trading'),
((SELECT id FROM categories WHERE slug = 'crypto-exchanges'), 'P2P Exchanges', 'p2p-exchanges', 'Peer-to-peer crypto marketplaces'),
((SELECT id FROM categories WHERE slug = 'hardware-wallets'), 'Ledger Devices', 'ledger-devices', 'Hardware wallets by Ledger'),
((SELECT id FROM categories WHERE slug = 'hardware-wallets'), 'Trezor Devices', 'trezor-devices', 'Hardware wallets by Trezor'),
((SELECT id FROM categories WHERE slug = 'software-wallets'), 'Mobile Wallets', 'mobile-wallets', 'Smartphone crypto wallets'),
((SELECT id FROM categories WHERE slug = 'software-wallets'), 'Browser Wallets', 'browser-wallets', 'Browser extension wallets'),
((SELECT id FROM categories WHERE slug = 'defi-tools'), 'Yield Aggregators', 'yield-aggregators', 'Automated yield farming protocols'),
((SELECT id FROM categories WHERE slug = 'defi-tools'), 'Lending Protocols', 'lending-protocols', 'Borrow and lend crypto assets'),
((SELECT id FROM categories WHERE slug = 'nft-platforms'), 'Marketplaces', 'nft-marketplaces', 'Buy and sell NFT collections'),
((SELECT id FROM categories WHERE slug = 'nft-platforms'), 'NFT Launchpads', 'nft-launchpads', 'Mint new NFT projects');

-- Insert sample companies
INSERT INTO companies (
  name, slug, description, short_description, website_url, logo_url,
  category_id, subcategory_id, tags, pricing_type, rating, review_count,
  is_featured, is_verified, affiliate_available, affiliate_url, affiliate_commission,
  countries_supported, pros, cons, features, founded_year, headquarters
) VALUES
(
  'Binance',
  'binance',
  'Binance is the worlds leading cryptocurrency exchange by trading volume, offering a comprehensive suite of trading products including spot trading, futures, options, and earn products. Founded in 2017, Binance has grown to serve millions of users globally with a focus on innovation, security, and user experience.',
  'Worlds largest crypto exchange with low fees and massive coin selection',
  'https://www.binance.com',
  'https://cryptologos.cc/logos/binance-coin-bnb-logo.png',
  (SELECT id FROM categories WHERE slug = 'crypto-exchanges'),
  (SELECT id FROM subcategories WHERE slug = 'centralized-exchanges'),
  ARRAY['exchange', 'trading', 'futures', 'spot', 'defi', 'launchpad', 'earn'],
  'freemium',
  4.8,
  1250,
  true,
  true,
  true,
  'https://www.binance.com/en/register?ref=YOUR_REF',
  'Up to 40% trading commission',
  ARRAY['Global', 'US (separate platform)', 'UK', 'EU', 'Asia'],
  ARRAY['Industry-leading trading volume', 'Low trading fees (0.1%)', '500+ cryptocurrencies supported', 'Advanced trading features', 'Binance Earn for passive income', 'Launchpad for new tokens'],
  ARRAY['Regulatory concerns in some countries', 'Complex interface for beginners', 'Customer support can be slow', 'US users need separate platform'],
  '{"spot_trading": true, "futures": true, "options": true, "earn": true, "launchpad": true, "nft_marketplace": true, "debit_card": true}',
  2017,
  'Cayman Islands'
),
(
  'Coinbase',
  'coinbase',
  'Coinbase is a US-based cryptocurrency exchange and one of the most trusted platforms for buying, selling, and storing digital assets. Known for its regulatory compliance and user-friendly interface, Coinbase is ideal for beginners entering the crypto space.',
  'Most trusted US crypto exchange, perfect for beginners',
  'https://www.coinbase.com',
  'https://cryptologos.cc/logos/coinbase-coin-logo.png',
  (SELECT id FROM categories WHERE slug = 'crypto-exchanges'),
  (SELECT id FROM subcategories WHERE slug = 'centralized-exchanges'),
  ARRAY['exchange', 'trading', 'defi', 'wallet', 'beginner-friendly'],
  'freemium',
  4.5,
  980,
  true,
  true,
  true,
  'https://www.coinbase.com/join/YOUR_REF',
  '$10 per referral signup',
  ARRAY['US', 'UK', 'EU', 'Canada', 'Australia', 'Singapore'],
  ARRAY['Extremely user-friendly interface', 'Strong regulatory compliance', 'FDIC insured USD deposits', 'Coinbase Earn program', 'Excellent mobile app', '24/7 customer support'],
  ARRAY['Higher fees than competitors', 'Limited coin selection', 'Advanced features require Coinbase Pro', 'Account restrictions possible'],
  '{"spot_trading": true, "futures": false, "earn": true, "debit_card": true, "pro_trading": true}',
  2012,
  'San Francisco, USA'
),
(
  'Ledger Nano X',
  'ledger-nano-x',
  'The Ledger Nano X is a Bluetooth-enabled hardware wallet that provides military-grade security for your cryptocurrency assets. With support for over 5,500 coins and tokens, it offers the perfect balance of security and convenience.',
  'Premium Bluetooth hardware wallet with 5,500+ supported coins',
  'https://www.ledger.com',
  'https://www.ledger.com/wp-content/uploads/2019/05/Ledger_Nano_X.png',
  (SELECT id FROM categories WHERE slug = 'hardware-wallets'),
  (SELECT id FROM subcategories WHERE slug = 'ledger-devices'),
  ARRAY['hardware-wallet', 'cold-storage', 'bluetooth', 'security', 'defi'],
  'paid',
  4.9,
  650,
  true,
  true,
  true,
  'https://shop.ledger.com/pages/ledger-nano-x?r=YOUR_REF',
  '15% commission on sales',
  ARRAY['Global'],
  ARRAY['Bluetooth connectivity', '5,500+ supported coins', 'Ledger Live app integration', 'Military-grade security (CC EAL5+)', 'Rechargeable battery', 'Mobile companion app'],
  ARRAY['Higher price point ($149)', 'No touch screen', 'Limited mobile coins via Bluetooth', 'Setup can be intimidating'],
  '{"bluetooth": true, "usb_type": "USB-C", "storage_count": 100, "battery": "110mAh", "security_chip": "CC EAL5+", "screen": "128x64px OLED"}',
  2019,
  'Paris, France'
),
(
  'Trezor Model T',
  'trezor-model-t',
  'The Trezor Model T is a premium hardware wallet featuring a color touchscreen and open-source firmware. Developed by SatoshiLabs, the pioneers of hardware wallets, it offers unparalleled transparency and security for serious crypto holders.',
  'Open-source hardware wallet with touchscreen and Shamir backup',
  'https://trezor.io',
  'https://trezor.io/static/images/model-t.png',
  (SELECT id FROM categories WHERE slug = 'hardware-wallets'),
  (SELECT id FROM subcategories WHERE slug = 'trezor-devices'),
  ARRAY['hardware-wallet', 'cold-storage', 'touchscreen', 'open-source', 'security'],
  'paid',
  4.8,
  420,
  false,
  true,
  true,
  'https://trezor.io/trezor-model-t?ref=YOUR_REF',
  '10% commission',
  ARRAY['Global'],
  ARRAY['Color touchscreen interface', 'Fully open-source firmware', 'Shamir backup encryption', 'MicroSD card encryption', 'FIDO2 authentication', 'USB-C connectivity'],
  ARRAY['Higher price ($219)', 'No Bluetooth', 'Larger form factor', 'No mobile companion'],
  '{"touchscreen": true, "usb_type": "USB-C", "sd_card": true, "security_chip": "STM32", "fido2": true, "shamir_backup": true}',
  2018,
  'Prague, Czech Republic'
),
(
  'Uniswap',
  'uniswap',
  'Uniswap is the leading decentralized exchange (DEX) protocol on Ethereum, enabling trustless token swaps through automated market making (AMM). As a pioneer in DeFi, Uniswap allows users to trade directly from their wallets without intermediaries.',
  'Largest Ethereum DEX with automated market making',
  'https://uniswap.org',
  null,
  (SELECT id FROM categories WHERE slug = 'crypto-exchanges'),
  (SELECT id FROM subcategories WHERE slug = 'decentralized-exchanges'),
  ARRAY['dex', 'defi', 'ethereum', 'amm', 'swap', 'liquidity'],
  'free',
  4.7,
  580,
  true,
  true,
  false,
  null,
  null,
  ARRAY['Global'],
  ARRAY['Non-custodial trading', 'No registration required', 'Permissionless listings', 'Liquidity provider rewards', 'Multi-chain support', 'Community governance'],
  ARRAY['Ethereum gas fees can be high', 'Slippage on large trades', 'No fiat on/off ramp', 'Smart contract risk'],
  '{"amm": true, "multichain": true, "governance": true, "nft_support": true}',
  2018,
  'Decentralized'
),
(
  'MetaMask',
  'metamask',
  'MetaMask is the most popular non-custodial wallet for interacting with the Ethereum blockchain and EVM-compatible networks. Available as a browser extension and mobile app, it serves as your gateway to Web3 applications.',
  'Most popular Web3 wallet for Ethereum and EVM chains',
  'https://metamask.io',
  null,
  (SELECT id FROM categories WHERE slug = 'software-wallets'),
  (SELECT id FROM subcategories WHERE slug = 'browser-wallets'),
  ARRAY['wallet', 'browser-extension', 'web3', 'ethereum', 'defi', 'nft'],
  'free',
  4.6,
  890,
  true,
  true,
  true,
  'https://metamask.io/download?ref=YOUR_REF',
  'Swaps affiliate revenue share',
  ARRAY['Global'],
  ARRAY['Easy Web3 integration', 'Built-in token swap', 'Multi-chain support', 'NFT display support', 'Hardware wallet connectivity', 'Mobile app available'],
  ARRAY['Browser only (no desktop app)', 'Phishing risk for beginners', 'Limited to EVM chains', 'No fiat purchases in some regions'],
  '{"browser_extension": true, "mobile_app": true, "swap": true, "hardware_wallet_support": true, "custom_networks": true}',
  2016,
  'San Francisco, USA'
),
(
  'CoinTracking',
  'cointracking',
  'CoinTracking is a comprehensive crypto tax software and portfolio tracker with support for over 100 exchanges and wallet integrations. Generate accurate tax reports in multiple formats and track your portfolio performance over time.',
  'Professional crypto tax and portfolio tracking for serious traders',
  'https://cointracking.info',
  null,
  (SELECT id FROM categories WHERE slug = 'crypto-tax-software'),
  null,
  ARRAY['tax', 'portfolio-tracker', 'accounting', 'reporting'],
  'freemium',
  4.5,
  310,
  true,
  true,
  true,
  'https://cointracking.info/?ref=YOUR_REF',
  '20% commission',
  ARRAY['Global'],
  ARRAY['100+ exchange integrations', 'Multiple tax report formats', 'Portfolio analytics', 'API integration', 'Historical price data', 'Cointracking Full Node'],
  ARRAY['Free plan limited to 200 transactions', 'Learning curve for advanced features', 'UI can feel dated', 'Customer support response time'],
  '{"exchanges": 100, "tax_reports": true, "portfolio_tracking": true, "api": true, "countries": 40}',
  2012,
  'Germany'
),
(
  'Koinly',
  'koinly',
  'Koinly is a user-friendly crypto tax calculator that automatically imports transactions from exchanges and wallets to generate accurate tax reports. Perfect for both beginners and professional traders across multiple jurisdictions.',
  'User-friendly crypto tax calculator with excellent CSV import',
  'https://koinly.io',
  null,
  (SELECT id FROM categories WHERE slug = 'crypto-tax-software'),
  null,
  ARRAY['tax', 'accounting', 'reporting', 'defi'],
  'freemium',
  4.7,
  420,
  true,
  true,
  true,
  'https://koinly.io/?ref=YOUR_REF',
  '25% commission',
  ARRAY['US', 'UK', 'Canada', 'EU', 'Australia'],
  ARRAY['Intuitive interface', 'Excellent CSV import', 'DeFi and NFT support', 'Multiple tax methods', 'TurboTax integration', 'Country-specific reports'],
  ARRAY['Free tier limited features', 'Some exchange sync issues', 'Pricing scales with transactions'],
  '{"exchanges": 300, "tax_methods": 20, "turbotax": true, "defi": true, "nft": true}',
  2018,
  'London, UK'
),
(
  '3Commas',
  '3commas',
  '3Commas is a leading crypto trading bot platform offering smart trading terminals, automated DCA bots, grid bots, and signal bots. Connect to major exchanges and automate your trading strategies.',
  'Powerful multi-exchange trading bot with DCA and grid strategies',
  'https://3commas.io',
  null,
  (SELECT id FROM categories WHERE slug = 'trading-bots'),
  null,
  ARRAY['trading-bot', 'dca', 'grid-bot', 'automation', 'signals'],
  'freemium',
  4.4,
  380,
  true,
  true,
  true,
  'https://3commas.io/?ref=YOUR_REF',
  '30% commission',
  ARRAY['Global'],
  ARRAY['Multi-exchange support', 'DCA and grid bots', 'Copy trading features', 'Smart trade terminal', 'Paper trading mode', 'Active community'],
  ARRAY['Subscription can be expensive', 'API issues during high volume', 'Learning curve', 'Customer support response time'],
  '{"exchanges": 17, "bots": 5, "copy_trading": true, "paper_trading": true, "api": true}',
  2017,
  'Estonia'
),
(
  'Coursera Crypto Courses',
  'coursera-crypto',
  'Coursera offers comprehensive cryptocurrency and blockchain courses from top universities including Princeton, University of Pennsylvania, and INSEAD. Learn fundamentals, smart contracts, and DeFi.',
  'University-level crypto education from top institutions',
  'https://www.coursera.org',
  null,
  (SELECT id FROM categories WHERE slug = 'crypto-education'),
  null,
  ARRAY['courses', 'education', 'blockchain', 'university', 'certification'],
  'freemium',
  4.8,
  250,
  true,
  true,
  true,
  'https://coursera.pxf.io/YOUR_REF',
  '45% commission',
  ARRAY['Global'],
  ARRAY['University-accredited courses', 'Certificates available', 'Self-paced learning', 'Financial aid available', 'Mobile access', 'High production quality'],
  ARRAY['Certificates require payment', 'Not crypto-specific platform', 'Course quality varies'],
  '{"courses": 50, "certificates": true, "universities": 200, "financial_aid": true}',
  2012,
  'Mountain View, USA'
),
(
  'CoinGecko',
  'coingecko',
  'CoinGecko is one of the largest cryptocurrency data aggregators, providing real-time prices, market analysis, and fundamental analysis for over 14,000 crypto assets. Essential research tool for any crypto investor.',
  'Leading crypto data aggregator with 14,000+ tracked assets',
  'https://www.coingecko.com',
  null,
  (SELECT id FROM categories WHERE slug = 'analytics-platforms'),
  null,
  ARRAY['analytics', 'price-tracking', 'research', 'api', 'data'],
  'free',
  4.9,
  720,
  true,
  true,
  false,
  null,
  null,
  ARRAY['Global'],
  ARRAY['Comprehensive data coverage', 'Free API available', 'Gecko Score ratings', 'Gecko Terminal DEX data', 'Trust Score metric', 'Educational content', 'Mobile app'],
  ARRAY['Free API rate limits', 'Some less popular coins missing data', 'Premium features behind paywall'],
  '{"tracked_coins": 14000, "api": true, "trust_score": true, "gecko_terminal": true, "mobile_app": true}',
  2014,
  'Malaysia'
);

-- Insert sample reviews
INSERT INTO reviews (company_id, author_name, rating, title, content, pros, cons, is_approved, is_verified_purchase) VALUES
((SELECT id FROM companies WHERE slug = 'binance'), 'CryptoTrader2024', 5, 'Best exchange for altcoins', 'Binance has been my go-to exchange for years. The variety of coins available is unmatched, and the trading fees are very competitive. Love the staking options too.', ARRAY['Huge coin selection', 'Low fees', 'Great mobile app'], ARRAY['Verification process took a while'], true, true),
((SELECT id FROM companies WHERE slug = 'binance'), 'BitcoinMaxi', 4, 'Solid exchange, watch the regulations', 'Great platform overall but regulatory issues in some countries can be frustrating. Make sure to check if its available in your region.', ARRAY['Professional features', 'Liquidity'], ARRAY['Complex KYC', 'Geographic restrictions'], true, true),
((SELECT id FROM companies WHERE slug = 'ledger-nano-x'), 'SecurityFirst', 5, 'Peace of mind for my crypto', 'The Ledger Nano X gives me confidence that my crypto is safe. The Bluetooth feature is convenient and Ledger Live makes it easy to manage multiple coins.', ARRAY['Top-notch security', 'Bluetooth convenience', 'Easy to use'], ARRAY['Pricey but worth it'], true, true),
((SELECT id FROM companies WHERE slug = 'metamask'), 'DeFi_Degen', 4, 'Essential Web3 tool', 'Cant use DeFi without MetaMask. Its become essential infrastructure for me. Just wish it had more chains by default.', ARRAY['Easy to use', 'Works everywhere', 'Regular updates'], ARRAY['Sometimes slow', 'Gas estimator inaccurate'], true, true),
((SELECT id FROM companies WHERE slug = 'koinly'), 'TaxTime2024', 5, 'Saved me hours on crypto taxes', 'Koinly imported all my transactions seamlessly. The tax report was accepted without issues. Worth every penny for serious traders.', ARRAY['Easy imports', 'Accurate reports', 'Great support'], ARRAY['Free tier too limited'], true, true);

-- Insert comparisons
INSERT INTO comparisons (company_a_id, company_b_id, slug)
SELECT c1.id, c2.id, 'binance-vs-coinbase'
FROM companies c1, companies c2
WHERE c1.slug = 'binance' AND c2.slug = 'coinbase';

INSERT INTO comparisons (company_a_id, company_b_id, slug)
SELECT c1.id, c2.id, 'ledger-nano-x-vs-trezor-model-t'
FROM companies c1, companies c2
WHERE c1.slug = 'ledger-nano-x' AND c2.slug = 'trezor-model-t';

-- Insert best-of lists
INSERT INTO best_of_lists (title, slug, description, category_id, is_published, order_index) VALUES
('Best Crypto Exchanges of 2024', 'best-crypto-exchanges', 'Our curated list of the top cryptocurrency exchanges ranked by fees, security, features, and user experience.', (SELECT id FROM categories WHERE slug = 'crypto-exchanges'), true, 1),
('Best Hardware Wallets 2024', 'best-hardware-wallets', 'Secure your crypto with the best hardware wallets. We evaluate security, ease of use, and coin support.', (SELECT id FROM categories WHERE slug = 'hardware-wallets'), true, 2),
('Best Crypto Tax Software', 'best-crypto-tax-software', 'Simplify tax season with these top-rated crypto tax calculators and reporting tools.', (SELECT id FROM categories WHERE slug = 'crypto-tax-software'), true, 3);

-- Insert items into best-of lists
INSERT INTO best_of_items (list_id, company_id, rank, blurb) 
SELECT 
  (SELECT id FROM best_of_lists WHERE slug = 'best-crypto-exchanges'),
  id,
  CASE WHEN slug = 'binance' THEN 1 WHEN slug = 'coinbase' THEN 2 WHEN slug = 'uniswap' THEN 3 END,
  CASE WHEN slug = 'binance' THEN 'Top choice for altcoins and advanced traders with lowest fees' WHEN slug = 'coinbase' THEN 'Best for US beginners seeking regulatory compliance' WHEN slug = 'uniswap' THEN 'Best decentralized exchange for trustless trading' END
FROM companies WHERE slug IN ('binance', 'coinbase', 'uniswap');

INSERT INTO best_of_items (list_id, company_id, rank, blurb)
SELECT 
  (SELECT id FROM best_of_lists WHERE slug = 'best-hardware-wallets'),
  id,
  CASE WHEN slug = 'ledger-nano-x' THEN 1 WHEN slug = 'trezor-model-t' THEN 2 END,
  CASE WHEN slug = 'ledger-nano-x' THEN 'Best balance of security and features with Bluetooth' WHEN slug = 'trezor-model-t' THEN 'Best open-source option with touchscreen' END
FROM companies WHERE slug IN ('ledger-nano-x', 'trezor-model-t');

-- Featured listings
INSERT INTO featured_listings (company_id, placement, start_date, end_date, is_active)
SELECT id, 'homepage_hero', NOW(), NOW() + INTERVAL '30 days', true FROM companies WHERE slug = 'binance';

INSERT INTO featured_listings (company_id, placement, start_date, end_date, is_active)
SELECT id, 'category_top', NOW(), NOW() + INTERVAL '30 days', true FROM companies WHERE slug = 'ledger-nano-x';